
Space.create(name: "Joes Garage")
Space.create(name: "Antones")
Space.create(name: "Continental Club")

Instrument.create(name: "Guitar")
Instrument.create(name: "Drums")
Instrument.create(name: "Piano")
Instrument.create(name: "Keyboard")
Instrument.create(name: "Violin")
Instrument.create(name: "Cello")


Genre.create(name: "Classic Rock")
Genre.create(name: "Jazz Combo")
Genre.create(name: "Blues Combo")
Genre.create(name: "Country Swing Band")
Genre.create(name: "Soul Review")
Genre.create(name: "Rap Group")
Genre.create(name: "String Quartet")
Genre.create(name: "Brass Quintet")
Genre.create(name: "Folk Band")
Genre.create(name: "Mariachi Band")


User.create(name: "Rick Glascock", email: "r@email.com", phone: "512-466-4190", bio: "I love RHCP and Strvainsky.",video: "https://www.youtube.com/embed/WmjQIHF2dAQ", password: "a")
User.create(name: "Nora Jones", email: "n@email.com", phone: "512-466-4190", bio: "I grew up singing in the church.", video: "https://www.youtube.com/embed/fd02pGJx0s0", password: "a")
User.create(name: "Aaiden Witten", email: "a@email.com", phone: "512-466-4190", bio: "Love the bossa Nova", password: "a")
User.create(name: "Joe Fernandez", email: "j@email.com", phone: "512-466-4190", bio: "Love the bossa Nova", password: "a")

UserInstrument.create(user_id: 1, instrument_id: 1)
UserInstrument.create(user_id: 1, instrument_id: 2)
UserInstrument.create(user_id: 2, instrument_id: 2)
UserInstrument.create(user_id: 2, instrument_id: 3)
UserInstrument.create(user_id: 3, instrument_id: 3)
UserInstrument.create(user_id: 3, instrument_id: 4)
UserInstrument.create(user_id: 4, instrument_id: 1)
UserInstrument.create(user_id: 4, instrument_id: 5)

GenreUser.create(genre_id: 1, user_id: 1)
GenreUser.create(genre_id: 2, user_id: 1)
GenreUser.create(genre_id: 2, user_id: 2)
GenreUser.create(genre_id: 3, user_id: 2)
GenreUser.create(genre_id: 3, user_id: 3)
GenreUser.create(genre_id: 2, user_id: 4)
