
Instrument.create(name: "Guitar")
Instrument.create(name: "Drums")
Instrument.create(name: "Piano")
Instrument.create(name: "Violin")
Instrument.create(name: "Cello")
Instrument.create(name: "Viola")
Instrument.create(name: "Bass-Guitar")
Instrument.create(name: "Standup-Bass")
Instrument.create(name: "Saxaphone")
Instrument.create(name: "Trumpet")
Instrument.create(name: "Horn")
Instrument.create(name: "Tuba")
Instrument.create(name: "Euphonium")
Instrument.create(name: "Trombone")
Instrument.create(name: "Clarinet")
Instrument.create(name: "Basoon")
Instrument.create(name: "Oboe")
Instrument.create(name: "Flute")
Instrument.create(name: "Turn-tables")
Instrument.create(name: "Melodica")
Instrument.create(name: "Accordian")
Instrument.create(name: "Vocals")
Instrument.create(name: "Harp")
Instrument.create(name: "Cahone")
Instrument.create(name: "Bongos")
Instrument.create(name: "Didgereedoo")
Instrument.create(name: "Tamborine")
Instrument.create(name: "Djembe")
Instrument.create(name: "Vibraphone")
Instrument.create(name: "Steel Drum")
Instrument.create(name: "Banjo")
Instrument.create(name: "Lap-steel Guitar")
Instrument.create(name: "Pipe-organ")

Space.create(name: "Rick's Garage", size: 'small' , address: "2218 Bordley Dr, 78748", description: "Good sized home studio. Has a baby grand, drums and vibraphone" )
Space.create(name: "Antones", size: 'large', address: "201 6th St., 78704", description: "Classic Austin Blues venue now at it's 5th location" )
Space.create(name: "Continental Club", size: "large" , address: "222 S. Congress, 78704", description: "Mediaum size stage. Good sound system. " )

Genre.create(name: "Classic Rock")
Genre.create(name: "Jazz Combo")
Genre.create(name: "Blues Combo")
Genre.create(name: "Country Swing Band")
Genre.create(name: "Soul Review")
Genre.create(name: "Rap Group")
Genre.create(name: "String Quartet")
Genre.create(name: "Brass Quintet")
Genre.create(name: "Folk Band")
Genre.create(name: "Mariachi Band")

User.create(name: "Rick Glascock", email: "r@email.com", phone: "512-466-4190", bio: "I love RHCP and Strvainsky.",video: "https://www.youtube.com/embed/WmjQIHF2dAQ", password: "a")
User.create(name: "Nora Jones", email: "n@email.com", phone: "512-466-4190", bio: "I grew up singing in the church.", video: "https://www.youtube.com/embed/fd02pGJx0s0", password: "a")
User.create(name: "Aaiden Witten", email: "a@email.com", phone: "512-466-4190", bio: "Love the bossa Nova", video: "https://www.youtube.com/embed/XyJiPzjvUMk", password: "a")
User.create(name: "Joe Fernandez", email: "j@email.com", phone: "512-466-4190", bio: "Love the bossa Nova", password: "a")
User.create(name: "Barry", email: "b1@email.com", phone: "512-466-4190", bio: "Love the bossa Nova", password: "a")
User.create(name: "Bob", email: "b2@email.com", phone: "512-466-4190", bio: "Love the bossa Nova", password: "a")
User.create(name: "Betty", email: "b3@email.com", phone: "512-466-4190", bio: "Love the bossa Nova", password: "a")
User.create(name: "Robert", email: "b4@email.com", phone: "512-466-4190", bio: "Love the bossa Nova", password: "a")

UserInstrument.create(user_id: 1, instrument_id: 1)
UserInstrument.create(user_id: 1, instrument_id: 2)
UserInstrument.create(user_id: 2, instrument_id: 2)
UserInstrument.create(user_id: 2, instrument_id: 3)
UserInstrument.create(user_id: 3, instrument_id: 3)
UserInstrument.create(user_id: 3, instrument_id: 4)
UserInstrument.create(user_id: 4, instrument_id: 1)
UserInstrument.create(user_id: 4, instrument_id: 5)
UserInstrument.create(user_id: 5, instrument_id: 7)
UserInstrument.create(user_id: 6, instrument_id: 7)
UserInstrument.create(user_id: 7, instrument_id: 7)
UserInstrument.create(user_id: 8, instrument_id: 7)

GenreUser.create(genre_id: 1, user_id: 1)
GenreUser.create(genre_id: 2, user_id: 2)
GenreUser.create(genre_id: 3, user_id: 3)
GenreUser.create(genre_id: 4, user_id: 4)

Jam.create(name: "Noras Monday Night Blues", space_id: 2, date: "03_09_20", time: "22:00:00")
