Jam.create(name: "The best jam")

Space.create(name: "Joes Garage")

Instrument.create(name: "Guitar")
Instrument.create(name: "Drums")
Instrument.create(name: "Piano")
Instrument.create(name: "Keyboard")
Instrument.create(name: "Violin")
Instrument.create(name: "Cello")
Instrument.create(name: "Viola")
Instrument.create(name: "Fiddle")
Instrument.create(name: "Bass-Guitar")
Instrument.create(name: "Standup-Bass")
Instrument.create(name: "Therobo")
Instrument.create(name: "Washboard")
Instrument.create(name: "Hurdy Gurdy")
Instrument.create(name: "Saxaphone")
Instrument.create(name: "Trumpet")
Instrument.create(name: "Horn")
Instrument.create(name: "Tuba")
Instrument.create(name: "Conette")
Instrument.create(name: "Euphonium")
Instrument.create(name: "Trombone")
Instrument.create(name: "Clarinet")
Instrument.create(name: "Basoon")
Instrument.create(name: "Oboe")
Instrument.create(name: "Flute")
Instrument.create(name: "Keytar")
Instrument.create(name: "Synthesizer")
Instrument.create(name: "Turn-tables")
Instrument.create(name: "Theremin")
Instrument.create(name: "Melodica")
Instrument.create(name: "Accordian")
Instrument.create(name: "Vocals")
Instrument.create(name: "Harp")
Instrument.create(name: "bandonean")
Instrument.create(name: "Squeeze-box")
Instrument.create(name: "Piano-flute")
Instrument.create(name: "Cahone")
Instrument.create(name: "Bongos")
Instrument.create(name: "Didgereedoo")
Instrument.create(name: "Tamborine")
Instrument.create(name: "Djembe")
Instrument.create(name: "Vibraphone")
Instrument.create(name: "Xylaphone")
Instrument.create(name: "Mirumba")
Instrument.create(name: "Glockenspiel")
Instrument.create(name: "Bells")
Instrument.create(name: "Steel Drum")
Instrument.create(name: "Banjo")
Instrument.create(name: "Lap-steel Guitar")
Instrument.create(name: "Pipe-organ")
Genre.create(name: "Rock")
Genre.create(name: "Jazz")
Genre.create(name: "Blues")
Genre.create(name: "Country")
Genre.create(name: "Soul")
Genre.create(name: "Rap")
Genre.create(name: "Classical")
Genre.create(name: "Oldies")
Genre.create(name: "Decades")
Genre.create(name: "Indie")
Genre.create(name: "Progressive Rock")
Genre.create(name: "Metal")
Genre.create(name: "Bluegrass")
Genre.create(name: "Latin")
Genre.create(name: "Flamenco")
Genre.create(name: "Mariachi")
Genre.create(name: "Polka")
Genre.create(name: "LoFi")
Genre.create(name: "Pop")
Genre.create(name: "Folk")